"""added user_profiles table and updated users

Revision ID: 0232484ab70e
Revises: 881bbe7b0c00
Create Date: 2021-01-25 10:24:15.389767

"""
import os
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy_searchable import sync_trigger
from sqlalchemy.orm import sessionmaker

Session = sessionmaker()


# revision identifiers, used by Alembic.

revision = '0232484ab70e'
down_revision = '881bbe7b0c00'
branch_labels = None
depends_on = None

def run_sqlalchemy_searchable_sql():
    migrations_folder = os.path.dirname(os.path.abspath(__file__))
    raw_sql = os.path.join(migrations_folder, 'expressions_script/expressions.sql')
    file = open(raw_sql)
    sql_expressions = sa.text(file.read())
    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute(sql_expressions)

def upgrade():
    run_sqlalchemy_searchable_sql()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('VIP', sa.Boolean(), nullable=True),
    sa.Column('background_img', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
